# Setup
title:               Learnings Cached
tagline:             'All pros were once amateurs'
description:         ''
url:                 https://shhafiz.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty
incremental: true

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y



